"""added supply request table relationship with user

Revision ID: 65acbd294d02
Revises: 93a5646c18fc
Create Date: 2020-10-01 14:40:35.828518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65acbd294d02'
down_revision = '93a5646c18fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplyrequest', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'supplyrequest', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplyrequest', type_='foreignkey')
    op.drop_column('supplyrequest', 'user_id')
    # ### end Alembic commands ###
