"""added supply request table

Revision ID: 93a5646c18fc
Revises: 
Create Date: 2020-10-01 14:28:13.719946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a5646c18fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplyrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productname', sa.String(length=60), nullable=True),
    sa.Column('total_required', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_status'),
    sa.UniqueConstraint('productname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplyrequest')
    # ### end Alembic commands ###
